---
title: Hackstrip
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hackstrip@github.com
description: A place for just some of my ramblings
baseurl: ''
url: ''
twitter_username: hackstrip
github_username: hackstrip
repository: hackstrip/hackstrip.github.io
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
show_downloads: false
